import { MedicationCatalogItem } from '../types';

export const DEFAULT_MEDICATION_CATALOG: MedicationCatalogItem[] = [
  {
    id: 'amoxicilina-001',
    name: 'Amoxicilina',
    category: 'Antibiótico',
    indication: 'Infecções bacterianas',
    prescription: 'Requer prescrição veterinária',
    application: 'Oral ou injeção',
    manufacturer: 'Vários',
  },
  {
    id: 'doxiciclina-001',
    name: 'Doxicilina',
    category: 'Antibiótico',
    indication: 'Infecções respiratórias e infecções gerais',
    prescription: 'Requer prescrição veterinária',
    application: 'Oral',
    manufacturer: 'Vários',
  },
  {
    id: 'enrofloxacino-001',
    name: 'Enrofloxacino',
    category: 'Antibiótico',
    indication: 'Infecções respiratórias, gastrointestinais',
    prescription: 'Requer prescrição veterinária',
    application: 'Oral ou injeção',
    manufacturer: 'Vários',
  },
  {
    id: 'vitamina-a-001',
    name: 'Vitamina A',
    category: 'Vitamina',
    indication: 'Deficiência de vitamina A, visão e imunidade',
    prescription: 'Venda livre',
    application: 'Oral ou injeção',
    manufacturer: 'Vários',
  },
  {
    id: 'vitamina-d-001',
    name: 'Vitamina D',
    category: 'Vitamina',
    indication: 'Deficiência de vitamina D, metabolismo do cálcio',
    prescription: 'Venda livre',
    application: 'Oral ou injeção',
    manufacturer: 'Vários',
  },
  {
    id: 'polivitaminico-001',
    name: 'Polivitamínico',
    category: 'Vitamina',
    indication: 'Suplementação vitamínica geral',
    prescription: 'Venda livre',
    application: 'Oral',
    manufacturer: 'Vários',
  },
  {
    id: 'ivermectina-001',
    name: 'Ivermectina',
    category: 'Antiparasitário',
    indication: 'Parasitas internos e externos',
    prescription: 'Requer prescrição veterinária',
    application: 'Oral, tópico ou injeção',
    manufacturer: 'Vários',
  },
  {
    id: 'albendazol-001',
    name: 'Albendazol',
    category: 'Antiparasitário',
    indication: 'Verminose interna',
    prescription: 'Requer prescrição veterinária',
    application: 'Oral',
    manufacturer: 'Vários',
  },
  {
    id: 'alcool-iodado-001',
    name: 'Álcool Iodado',
    category: 'Desinfetante',
    indication: 'Desinfecção de feridas e higienização',
    prescription: 'Venda livre',
    application: 'Tópico',
    manufacturer: 'Vários',
  },
  {
    id: 'agua-oxigenada-001',
    name: 'Água Oxigenada',
    category: 'Desinfetante',
    indication: 'Limpeza e desinfecção de feridas',
    prescription: 'Venda livre',
    application: 'Tópico',
    manufacturer: 'Vários',
  },
  {
    id: 'probiotico-001',
    name: 'Probiótico',
    category: 'Outro',
    indication: 'Saúde intestinal, flora bacteriana',
    prescription: 'Venda livre',
    application: 'Oral',
    manufacturer: 'Vários',
  },
  {
    id: 'vitamina-c-001',
    name: 'Vitamina C',
    category: 'Vitamina',
    indication: 'Reforço imunológico',
    prescription: 'Venda livre',
    application: 'Oral ou injeção',
    manufacturer: 'Vários',
  },
];
